### ISSUE TITLE
saveBook 구현

### ISSUE THREAD

**Issue by hun8729** [hun8729/MiniProject#10]
saveBook을 할 때 booklist.txt에 저장을 위해서 Library에 있는 내용들을 저장하고 Book내용들중 겹치지 않는 내용들을 저장해야하는데 조금 어려움이 있는데 혹시 좋은 생각 있으신가요?

**Comment by hwan129** [comment]
booklist.txt에는 반납한 책 넣고 book에는 반납 안된 책만 넣는 건 어떨까요?

**Comment by hun8729** [comment]
책이 반납이 되어서 booklist.txt에 기록이 되고 다시 같은 이름의 책을 빌리게 된다면 같은 책이 또 있는걸로 하나요 아니면 booklist.txt에서 지우는걸로 할까요?
