### ISSUE TITLE
recommandBook

### ISSUE THREAD

**Issue by hwan129** [hun8729/MiniProject#11]
프로그램을 껐다가 키면 returningstate가 구조체 Book에 따로 들어가지가 않네요. returning state를  한 스트럭처에만 넣던가 loaddata 할 때 구조체 Book에도 불러 오던가 해야 할 것 같습니다

**Comment by hwan129** [comment]
바꾸려 시도 해봤는데 잘 안되네요....

**Comment by hun8729** [comment]
다시 보니 저희가 저장할 때 reutrningstate를 안 파일에 안적어서 저장이 안되서 불러오지 못했던 것 같습니다 그 부분은 제가 수정하겠습니다.
