### ISSUE TITLE
booklist.txt 정리

### ISSUE THREAD

**Issue by hun8729** [hun8729/MiniProject#12]
말씀하신대로 booklist.txt파일에는 반납된 책들만 저장하는 것으로 진행하는 것이 좋은거 같습니다.
그러면 저희가 저장할 때 struct book에서 반납된 책들은 먼적 fprint하고 Library에 있는 책들 중 이름이 겹치지 않는 책들을 저장해야하는데 계속 if문을 걸어서 하니 오류가 나서 지금 못하고 있는데 방법을 함께 찾아주시면 감사하겠습니다. 
그리고 이렇게 되면 랜덤책 추천도 library struct를 이용해서 진행하는 것이 좋을것 같은데 어떻게 생각하시나요?

**Comment by hwan129** [comment]
빌리거나 수정하거나 반납할 때, Library struct를 다 사용해야 할 거 같아요.
아니면 booklist에 빌릴 수 있는 책들을 고정 시켜 놓고, book에는 지금처럼 빌린 사람들 리스트를 저장하는 방식은 어떨까요.

**Comment by hun8729** [comment]
booklist에 빌릴 수 있는 책들을 고정시키는것은 어떤 책들을 고정시키나요? 그냥 저희가 임의의 책들을 넣어두자는것을 말씀하시는건가요?

**Comment by hwan129** [comment]
도서관에 책들이 있듯이 booklist에 책들을 고정으로 저장해 두는거죠. 그냥 아무 책들이나. 누가 빌려가거나 반납하면 returningstate만 변경시키고

**Comment by hun8729** [comment]
그렇게 하면 저희가 따로 데이터베이스를 쓸 수 있는 상황도 아니라 제공하는 데이터가 너무 적을거 같은데 Library를 load하는 함수도 따로 구현하고 반납을 하면 그 때 책이름을 library에 넣으면서 하는건 어떨까요

**Comment by hwan129** [comment]
제공하는 데이터는 왜 줄어드는지 모르겠네요
지금 library도 같이 load하고 있지 않나
그럼 save 할 땐 대출이니까 book에 넣고 delete 할 땐 반납이니까 booklist에 넣고 book에는 지우고, 만약 booklist에 있는 책을 대출 할 땐 booklist에서 지우고 book 에는 추가해야겠네요

**Comment by hun8729** [comment]
제가 말하는거는 저희가 제공하는 책을 지정하고 시작하면 빌릴 수 있는 책의 수가 30권정도로 제한해버리는걸 말하고 있었습니다.
library를 load하는 함수를 따로 구현해서 library의 갯수도 따로 알고 있으면 다른 함수들을 구현할 때 편할거 같습니다 delete할 때는 book은 returningstate를 1로 바꾸고 library에는 추가를 하는거죠  
넵 strcmp를 이용하면 구현 할 수 있지 않을까요?

**Comment by hun8729** [comment]
반납 저장 불러오기는 제가 고치고 있으니 빌리는 부분만 수정해주실 수 있으신가요?

**Comment by hwan129** [comment]
main에서 이미 30으로 제한되어있어서 똑같을 거 같네
알겠습니다

**Comment by hwan129** [comment]
일단 내 생각대로 바꿨는데 너 바꾸는거 보고 다시 수정해볼게
잘 못 한 부분 수정했음

**Comment by hwan129** [comment]
recommand는 CRUD확정되면 다시 수정할게

**Comment by hun8729** [comment]
제가 한 것도 공유 해드릴게요
