### ISSUE TITLE
반납일 설정

### ISSUE THREAD

**Issue by hwan129** [hun8729/MiniProject#2]
반납하는 달과 일을 short int로 받는 이유가 뭔가요.
반납하는 일을 2023.05.09 이렇게 받는 건 어떤가요?

**Comment by hun8729** [comment]
메모리 낭비 방지를 위해서 short int로 한건고 나중에 현재 날짜를 입력받아서 반납 날과 비교하여 연체를 확인해야하니 short int를 사용했고 년도까지 해서 해도 좋을 거 같습니다.
