### ISSUE TITLE
부가기능 구현

### ISSUE THREAD

**Issue by hun8729** [hun8729/MiniProject#3]
selectmenu와 같은 다른 부가기능 구현 함수들은 다른 파일을 만들어서 구현하는거 어떤가요?

**Comment by hwan129** [comment]
다른 .c파일을 만들자는건가요?

**Comment by hun8729** [comment]
네 그렇게 하면 함수들을 보고 정리하는게 좋을 거 같습니다

**Comment by hwan129** [comment]
그렇게 하는 이유가 더 있나요? 부가기능 함수들도 많아서 나누려면 더 많이 나눠야할 거 같은데

**Comment by hwan129** [comment]
아니면 사용하는 텍스트 파일에 따라 따로 정리하는건 어떤가요

**Comment by hwan129** [comment]
좋습니다
